# Generated by Django 6.0 on 2025-12-06 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('PETROL', 'Petrol'), ('MAINTENANCE', 'Vehicle Maintenance'), ('FOOD', 'Meals while working'), ('PHONE', 'Data/Phone Bill'), ('EQUIPMENT', 'Equipment/Gear'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform', models.CharField(choices=[('GRAB', 'Grab'), ('FOODPANDA', 'FoodPanda'), ('LALAMOVE', 'Lalamove'), ('SHOPEEFOOD', 'ShopeeFood'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=1, help_text='Hours spent working for this income', max_digits=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
