-- =====================================================
-- SideDuit Complete Database Setup
-- Run this in Supabase SQL Editor
-- =====================================================

-- Step 1: Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 2: Create transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
  id bigint generated by default as identity primary key,
  year int,
  date date not null,
  time time without time zone,
  transaction_type text not null,
  transaction_amount numeric(10, 2) not null,
  document_id text,
  upload_id bigint,
  user_id text default '0',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Step 3: Create upload logs table
CREATE TABLE IF NOT EXISTS public.update_logs (
  upload_id bigint generated by default as identity primary key,
  upload_user text,
  upload_document_name text,
  uploaded_document bytea,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Step 4: Create transaction embeddings table for RAG
CREATE TABLE IF NOT EXISTS public.transaction_embeddings (
  embedding_id bigint generated by default as identity primary key,
  transaction_id bigint,
  upload_id bigint,
  
  -- Document content and metadata
  original_text text not null,
  document_name text,
  document_type text, -- 'receipt', 'invoice', 'statement', 'payslip', 'gig_receipt', 'bill'
  
  -- Vector embedding (768 dimensions for text-embedding-004)
  embedding vector(768) not null,
  
  -- Category and classification
  transaction_category text, -- e.g. 'Food-Restaurant', 'Transport-Ride', 'Income-Freelance'
  merchant_name text,
  amount numeric(10, 2),
  transaction_date date,
  
  -- Confidence scores
  classification_confidence numeric(3, 2), -- 0.00 to 1.00
  
  -- Metadata
  user_id text default '0',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Foreign key constraints
  CONSTRAINT fk_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE,
  CONSTRAINT fk_upload FOREIGN KEY (upload_id) REFERENCES public.update_logs(upload_id) ON DELETE CASCADE
);

-- Step 5: Create indexes for transactions
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);
CREATE INDEX IF NOT EXISTS idx_transactions_type ON public.transactions(transaction_type);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_created_at ON public.transactions(created_at DESC);

-- Step 6: Create indexes for upload logs
CREATE INDEX IF NOT EXISTS idx_update_logs_user ON public.update_logs(upload_user);
CREATE INDEX IF NOT EXISTS idx_update_logs_created_at ON public.update_logs(created_at DESC);

-- Step 7: Create indexes for embeddings
CREATE INDEX IF NOT EXISTS idx_embeddings_transaction_id ON public.transaction_embeddings(transaction_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_upload_id ON public.transaction_embeddings(upload_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_user_id ON public.transaction_embeddings(user_id);
CREATE INDEX IF NOT EXISTS idx_embeddings_category ON public.transaction_embeddings(transaction_category);
CREATE INDEX IF NOT EXISTS idx_embeddings_date ON public.transaction_embeddings(transaction_date);
CREATE INDEX IF NOT EXISTS idx_embeddings_created_at ON public.transaction_embeddings(created_at DESC);

-- Step 8: Create HNSW index for fast vector similarity search
-- This is the most important index for RAG/semantic search
CREATE INDEX IF NOT EXISTS idx_embeddings_vector ON public.transaction_embeddings 
USING hnsw (embedding vector_cosine_ops);

-- Step 9: Insert sample data (optional - for testing)
INSERT INTO public.transactions (date, time, transaction_type, transaction_amount, user_id)
VALUES 
  ('2024-12-01', '10:30:00', 'Income', 250.00, '0'),
  ('2024-12-02', '14:15:00', 'Income', 180.50, '0'),
  ('2024-12-03', '09:00:00', 'Income', 320.00, '0'),
  ('2024-12-04', '16:45:00', 'Income', 420.75, '0'),
  ('2024-12-05', '11:20:00', 'Income', 195.00, '0'),
  ('2024-12-01', '08:00:00', 'Expense', 50.00, '0'),
  ('2024-12-02', '12:30:00', 'Expense', 35.50, '0'),
  ('2024-12-03', '18:00:00', 'Expense', 80.00, '0'),
  ('2024-12-04', '13:15:00', 'Expense', 25.00, '0'),
  ('2024-12-05', '19:30:00', 'Expense', 120.00, '0')
ON CONFLICT DO NOTHING;

-- Step 10: Verify setup
SELECT 
  'transactions' as table_name, 
  COUNT(*) as row_count 
FROM public.transactions
UNION ALL
SELECT 
  'update_logs' as table_name, 
  COUNT(*) as row_count 
FROM public.update_logs
UNION ALL
SELECT 
  'transaction_embeddings' as table_name, 
  COUNT(*) as row_count 
FROM public.transaction_embeddings;

-- Success message
DO $$
BEGIN
  RAISE NOTICE '✅ SideDuit database setup complete!';
  RAISE NOTICE '📊 Tables created: transactions, update_logs, transaction_embeddings';
  RAISE NOTICE '🔍 Vector search enabled with HNSW index';
  RAISE NOTICE '🚀 Ready for uploads with RAG/MCP support!';
END $$;

