-- Updated schema with user_id for multi-user isolation
CREATE TABLE public.transactions (
  id bigint generated by default as identity primary key,
  year int,
  date date not null,
  time time without time zone,
  transaction_type text,
  transaction_amount numeric(10, 2),
  document_id text,
  user_id bigint,  -- For multi-user data isolation
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create index on user_id for faster queries
CREATE INDEX idx_transactions_user_id ON public.transactions(user_id);

-- Optional: If you have Django's auth_user table, add foreign key
-- ALTER TABLE public.transactions 
-- ADD CONSTRAINT fk_transactions_user 
-- FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE CASCADE;
