-- Table to store upload logs and file content
CREATE TABLE public.update_logs (
  upload_id bigint generated by default as identity primary key,
  upload_user text,
  upload_document_name text,
  uploaded_document bytea, -- Binary data for the file
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Index for faster lookup by user
CREATE INDEX idx_update_logs_user ON public.update_logs(upload_user);
