-- Table for storing document embeddings for RAG and MCP
-- Supports semantic search and AI-powered insights

CREATE TABLE IF NOT EXISTS public.transaction_embeddings (
  embedding_id bigint generated by default as identity primary key,
  transaction_id bigint,
  upload_id bigint,
  
  -- Document content and metadata
  original_text text not null,
  document_name text,
  document_type text, -- 'receipt', 'invoice', 'statement', etc.
  
  -- Vector embedding (dimension depends on model, gemini-text-embedding-001 uses 768)
  embedding vector(768) not null,
  
  -- Category and classification
  transaction_category text, -- 'Food', 'Transport', 'Income-Freelance', etc.
  merchant_name text,
  amount numeric(10, 2),
  transaction_date date,
  
  -- Confidence scores
  classification_confidence numeric(3, 2), -- 0.00 to 1.00
  
  -- Metadata
  user_id text default '0',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Foreign key constraints
  CONSTRAINT fk_transaction FOREIGN KEY (transaction_id) REFERENCES public.transactions(id) ON DELETE CASCADE,
  CONSTRAINT fk_upload FOREIGN KEY (upload_id) REFERENCES public.update_logs(upload_id) ON DELETE CASCADE
);

-- Indexes for fast retrieval
CREATE INDEX idx_embeddings_transaction_id ON public.transaction_embeddings(transaction_id);
CREATE INDEX idx_embeddings_upload_id ON public.transaction_embeddings(upload_id);
CREATE INDEX idx_embeddings_user_id ON public.transaction_embeddings(user_id);
CREATE INDEX idx_embeddings_category ON public.transaction_embeddings(transaction_category);
CREATE INDEX idx_embeddings_date ON public.transaction_embeddings(transaction_date);

-- Enable pgvector extension for similarity search (if not already enabled)
-- Run this first in Supabase SQL Editor:
-- CREATE EXTENSION IF NOT EXISTS vector;

-- Index for vector similarity search (HNSW is faster for large datasets)
CREATE INDEX idx_embeddings_vector ON public.transaction_embeddings 
USING hnsw (embedding vector_cosine_ops);

-- Comment on table
COMMENT ON TABLE public.transaction_embeddings IS 'Stores vector embeddings of transactions for RAG, semantic search, and MCP integration';

